### PR TITLE
WIP: Browsersync

### PR DESCRIPTION
**Pull request by xvilo**
This PR adds `browser-sync` to the gulp task, it's infinitely better than `Live Reload`. It works, a bit. Need to get some more things ironed out first.

### CODE REVIEW

**Comment by xvilo** [comment]
With live reload you'll need a browser plugin, this is not needed for Browser Sync. Scrolling is synced so you can have it on multiple browsers and then click and scroll through the site and see all other browsers (windows) change with it. This works for both mobile and desktop :D

**Comment by diggerhub** [comment]
we were planing on using [gulp-connect] (https://github.com/avevlad/gulp-connect) but this does look better.

**Comment by thumbnail** [comment]
Could you update the documentation? Looks alright, will test locally and approve as soon as the readme is updated 🙆.

Thanks

**Review by hampterhub — COMMENTED** [review]
image
got lots of 404's so i changed  `/dist/main.css` to `../dist/main.css` for all the effected files, funny thing  is that the favicon just loads without it.
@thumbnail will making this change effect the CI in any way? 
@xvilo browser-sync works great, nice!

**Comment by thumbnail** [comment]
@diggerhub I added the `baseurl` option when we switched to our own CI; because everything is served at `delta-leonis.github.io/website`. Changing it will break the link with the assets on production.  I'm not sure why you're getting the errors.

**Comment by diggerhub** [comment]
Well if you don't have this issue then I guess it's a local problem with my system and we can approve the PR

**Comment by xvilo** [comment]
I appreciate your enthusiasm, but it is clearly marked as _Work In Progress_ I had several issues too with this setup, do these need to be ironed out first. I'll poke you guys when it is ready! :D

**Pull request closed without merging**
